### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by benjaminao** [sheikalthaf/ngx-carousel#11]
Excellent work, I love the carousel, especially for what configurable, but it is giving me an error:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '1,1,1,1'. NgxCarouselComponent.html:1 

I hope you can help me

**Comment by sheikalthaf** [comment]
It's a known error but it doesn't affect the carousel. Fix is coming in the next release
Thanks for your support and love

**Comment by sheikalthaf** [comment]
This issue is fixed in the latest build 1.2.0. Also this build has some changes don't forget to read readme and changlelog file
