### ISSUE TITLE
Buttons unresponsive for a few seconds at a time.

### ISSUE THREAD

**Issue by craftyInstigator** [sheikalthaf/ngx-carousel#12]
There seems to be an issue where the buttons are unresponsive for a few seconds. Then they do work for a few seconds, and as long as you keep clicking they continue working. I you stop clicking for a few seconds, the buttons stop working again for a few seconds. 

I was able to run into this issue in Google Chrome using the basic banner example.

**Comment by sheikalthaf** [comment]
hi,
      which angular version you are using?
      I have not faced this issue before. i will try to update the button event, maybe it will solve the issue.
Thanks for reporting

**Comment by craftyInstigator** [comment]
Hi,
First of all, thank you for this excellent carousel. The version of Angular I'm using is 4.4.4.

**Comment by sheikalthaf** [comment]
build 1.2.0 is released. before updating read once readme and changelog file. after the update if you face this issue comment here or otherwise close this issue. thank for the support

**Comment by craftyInstigator** [comment]
This problem is resolved in 1.2.0, and everything is working perfectly. Thank you very much!
