### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by bresleveloper** [sheikalthaf/ngx-carousel#13]
hi, Demo looks awesome, and i want to use it but cant.

1st error, copying the example from the readme.md, is from line `public carouselBanner: Carousel;` error: `Cannot find name 'Carousel'`.

if i change it to `public carouselBanner: NgxCarousel` its ok.

but then in the browser
```compiler.es5.js:1694 Uncaught Error: Template parse errors:
Unexpected closing tag "ngx-carousel". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
  <button class='leftRs'>&lt;</button>
  <button class='rightRs'>&gt;</button>
[ERROR ->]</ngx-carousel> 
```

please help me.

p.s.
using angular 4.4.3

**Comment by aakashbumiya94** [comment]
same issue

**Comment by aakashbumiya94** [comment]
pls help!

**Comment by sheikalthaf** [comment]
Hello,
I'm updating tomorrow with all the issue fixed.
Check back tomorrow

Thanks for your support

**Comment by bresleveloper** [comment]
if you're in that already, perhaps you could also add some simple fixes made in this fork:
https://github.com/amitchawla22/ngx-carousel

**Comment by sheikalthaf** [comment]
Unexpected closing tag "ngx-carousel" because i missed the backslash 'ngx-item' closing tag. Sorry for the mistake. I'm also pushing the update now with proper demo

**Comment by sheikalthaf** [comment]
pushed the update. Please read the changelog and readme file before upgrading. it have some changes

**Comment by bresleveloper** [comment]
my friend, you must create a new project, npm your repo and test.

my friend i have some issues for you.

#### 1 - Property 'dynamicLength' is missing

the "new" error is:
```
ERROR in C:/Users/admin/Documents/Angular 4/my-dream-app/src/app/Pages/dream-home/dream-home.component.ts (77,5): Type '{ grid: { xs: number; sm: number;
 md: number; lg: number; all: number; }; slide: number; speed: n...' is not assignable to type 'NgxCarousel'.
  Property 'dynamicLength' is missing in type '{ grid: { xs: number; sm: number; md: number; lg: number; all: number; }; slide: number; speed: n...'.
```

since `dynamicLength` is not optional (`?`).

#### 2 - `carouselBannerLoad` example
it adds many items, but no buttons down the slides stating there are more items are added with it.

#### 3 - [issue 11](https://github.com/sheikalthaf/ngx-carousel/issues/11) is showing again
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '1,1,1,1,1'.` 

it does not really matter that it doesnt affect anything, you cant go into a project with a static error.


please fix the issues since its a really really cool carousel and i would love to use it in all my projects.
