### ISSUE TITLE
1 slide grid - center item smaller then 100% width

### ISSUE THREAD

**Issue by shaniqwa** [sheikalthaf/ngx-carousel#15]
Hi, great carousel. I'm trying to change the grid of 1 element to 80% width, but that cause the item to appear on the side and not centering. the purpose is that the neighbors of each item are a little shown on the sides, suggesting there is more to see. I couldn't  change the transform property to make this work.
I think this grid would be useful to others.
thanks

*edit*
basically if I use the fixed width grid, that's almost what I want - but still items are not centered and with width is only in pixels, % not supported (which would be awesome)

**Comment by sheikalthaf** [comment]
I thing you want your item width to be 80% but still want to show 1 item per display. if I'm right then do this. make your grid to be 1.
then create a div inside `ngx-item` and set it` width` to` 80%` and `margin` to `0 auto` 
now your div will be in center.
if this is not the solution then show me the screenshot of the result you are getting?

**Comment by shaniqwa** [comment]
that didn't work because the item was still inside a bigger div, here's the result: 

![capture2](https://user-images.githubusercontent.com/9408766/31426955-33fe2674-ae6e-11e7-90f9-f80643ee1246.PNG)

I had to edit some code to get this to work, that's the result I wanted: 
![capture](https://user-images.githubusercontent.com/9408766/31427037-85d0cc2c-ae6e-11e7-9ce4-23dc5e41e423.PNG)

I added this css to change the item width: 
`/deep/ div.ngxcarousel > div > div.ngxcarousel-items > ngx-tile > div {
  width: 90% !important;
}`

and in ngx-carousel.component.js I changed the `transformStyle` function to calculate the transform so it's in the middle when changing slides:
`this.data.transform.xs = Math.abs(5-(90 / this.userData.grid.xs * slide));;`

looks great now. I should probably fork this to keep my changes

**Comment by sheikalthaf** [comment]
Looks great. Hope you enjoying the carousel. If your problem solved then close this issue
