### ISSUE TITLE
Need point controls to change slide on click

### ISSUE THREAD

**Issue by nbiles** [sheikalthaf/ngx-carousel#17]
I can't use this until you can add the option where on point controls/circles click it will navigate to that slide.

Thanks!

**Comment by sheikalthaf** [comment]
I will make this feature available on next update. Thanks

**Comment by OsyaLdn** [comment]
I agreed with @nbiles it will be great add on point controls, thanks

**Comment by sheikalthaf** [comment]
already done that. Just need to push the update

**Comment by OsyaLdn** [comment]
@sheikalthaf  sorry, for disturbing you, when you planned update the repository?

**Comment by sheikalthaf** [comment]
Update now live. v1.2.5

**Comment by sheikalthaf** [comment]
don't forget to check the readme and changelog file. Now I'm closing the issue

**Comment by sheikalthaf** [comment]
check demo https://sheikalthaf.github.io/ngx-carousel/
