### ISSUE TITLE
Left/Right button don't work in FireFox

### ISSUE THREAD

**Issue by philoliver** [sheikalthaf/ngx-carousel#2]
Hi,
First, thanks for making this neat component available!

I experience an issue in FireFox. The left/right buttons don't work on my Mac. Exception:"TypeError: event.srcElement is undefined".

I was able to temporarily fix it by replacing the following line:
```
var btn = event.srcElement.classList;
```
with 
```
var element = event.target || event.srcElement
var btn = element.classList;
```

Cheers,
Philipp

**Comment by sheikalthaf** [comment]
hello,
Thanks for your appreciation.

Thanks for the issue and the solution. Updated the code and i will push the update with some new options today. 

I'm lack of testing. If you find any  issues please create a issue and i love to solve problems.  Hope you enjoying the carousel.

Sheik Althaf

**Comment by sheikalthaf** [comment]
Updated the carousel with this bug fixing and more. Please read CHANGELOG.md file for more details
