### ISSUE TITLE
touch scrolling down

### ISSUE THREAD

**Issue by AlexanderGubskyy** [sheikalthaf/ngx-carousel#20]
Hello, when I scroll down my page (and touch carousel), banner changes position right or left. your test example has same problem. It looks like a very big bug. How to fix it? Thanks

**Comment by sheikalthaf** [comment]
hi,
It is a known issue but it doesn't effect the carousel. I'm already looking into it.
Thanks

**Comment by eisventura** [comment]
I would be very grateful if this problem will be fixed

**Comment by sheikalthaf** [comment]
@AlexanderGubskyy @eisventura fixed this issue in build v1.3.2. read the changelog file
