### ISSUE TITLE
Set Default/Active slide

### ISSUE THREAD

**Issue by sovm** [sheikalthaf/ngx-carousel#21]
Hi, is there any way I can set a default slide onInit, rather than just default to first slide?

**Comment by sheikalthaf** [comment]
hello,
currently this feature is not available. I will add this feature in next update.
thanks for the suggestion

**Comment by sheikalthaf** [comment]
Added this feature in latest build 1.3.0. `moveToSlide` is an `Input` and it accepts numbers.
thanks for your suggestion
