### ISSUE TITLE
Swipe on IPad  doesn't work

### ISSUE THREAD

**Issue by OsyaLdn** [sheikalthaf/ngx-carousel#22]
Swiping doesn't work on iPads in Portrait mode.
I can't debugged, where is the problem

**Comment by sheikalthaf** [comment]
hi,
which browser you are using. I don't have ipad to test.
Any info about the issue so that i can help

**Comment by sumithmano** [comment]
Also swipping doesn't work on iPhones also.
Iphone 6, Chrome, iOS11

It is reproducible with your demo https://sheikalthaf.github.io/ngx-carousel/ . 
Just swipe at second example - 'tiles example'.

**Comment by sheikalthaf** [comment]
I have a workaround. I will make it possible to fix this problem in the next update. 
Thanks for reporting

**Comment by sheikalthaf** [comment]
This issue is fixed in latest build 1.3.0. check it and close the issue
Thanks for reporting

**Comment by sheikalthaf** [comment]
will you please confirm the issue with v1.3.0?

**Comment by sheikalthaf** [comment]
@OsyaLdn please confirm the issue with v1.3.0. If it is fixed close this issue

**Comment by jtbairdsr** [comment]
I can confirm updating fixed the problem for me.

**Comment by sheikalthaf** [comment]
Thanks for your confirmation

**Comment by shurvirmori** [comment]
I am not able to swipe on Laptop resolution , 
chrome latest version , windows 8, and ngx-carousel- v1.3.5
once i try to swipe, then stop working my navigation buttons.

**Comment by dummy64** [comment]
Hey, i am using latest version , but i am not able to swipe in ios devices
