### ISSUE TITLE
Hide points in navigation

### ISSUE THREAD

**Issue by LauraAlb** [sheikalthaf/ngx-carousel#24]
Hello! 

With this config: 

    this.lmmCarouselOne = {
      grid: {xs: 1, sm: 1, md: 1, lg: 1, all: 0},
      slide: 1,
      speed: 400,
      interval: 0,
      point: {
        visible: **false**
      },
      load: 2,
      touch: true,
      loop: false
    }

An error appears in the console: 

 ERROR TypeError: Cannot read property 'nativeElement' of undefined

**Comment by sheikalthaf** [comment]
hi,
fixed the bug. Thanks for reporting.
Also Thanks for your support

**Comment by LauraAlb** [comment]
Thank you!!

**Comment by anuruddha-thennakoon** [comment]
When will be the next update release?waiting for fixed bug mentioned above.

**Comment by sheikalthaf** [comment]
Currently I'm out of station more than a week. I will update it tomorrow if possible.

For now u can fix it by removing point from above instead of making false.

Thanks

**Comment by anuruddha-thennakoon** [comment]
Thanks

**Comment by sheikalthaf** [comment]
This bug is fixed in latest build 1.3.0
Thanks for reporting
