### ISSUE TITLE
min slide item size

### ISSUE THREAD

**Issue by musaay** [sheikalthaf/ngx-carousel#25]
Hello

I wanna show arrows if more than x items. Can you help me?

**Comment by sheikalthaf** [comment]
hi,
Sure  I will add a `eventemitter` to the carousel which will trigger on slides. it will also output some data. I will  give you the interface in the readme file. you can validate the x items or whatever you want.
please wait for the next update
what is your angular version?
thanks.

**Comment by musaay** [comment]
Hi,

Our angular version is 2.2.3.

**Comment by musaay** [comment]
Is there any news for this issue?

**Comment by sheikalthaf** [comment]
I have added a `onMove` output which will trigger on each slide. check the get started  guide in readme file

**Comment by musaay** [comment]
I dont understand onMove. For example, i have one item and dont wanna show arrows. How can i do that. Can you give an example
