### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by dave-renalds** [sheikalthaf/ngx-carousel#28]
If I have a carousel with a total of 5 images and I show 4 images at a time when I click next it is all fine, but then the back button doesn't work.

I'm showing images from a search result, so I don't know how many total images I will have in the carousel. Here's my settings:

        this.carouselTile = {
            grid: { xs: 4, sm: 4, md: 4, lg: 4, all: 0 },
            slide: 4,
            speed: 400,
            interval: 0,
            point: {
                visible: false,
                pointStyles: `
                `
            },
            touch: false,
            loop: false,
            custom: 'banner'
        };

**Comment by fwdnickv** [comment]
I have the same issue. Enabling looping seems to fix my issues with the back/forward buttons.

**Comment by sheikalthaf** [comment]
hello,
fixed this issue now. It will be fixed in upcoming update
Thanks

**Comment by sheikalthaf** [comment]
This bug is fixed in the latest build 1.3.0
Thanks for reporting
