### ISSUE TITLE
Number of points is incorrect on grid size change

### ISSUE THREAD

**Issue by fwdnickv** [sheikalthaf/ngx-carousel#29]
I setup a carousel with the following settings:
`  public carouselSettings: NgxCarousel = {
    grid: {xs: 1, sm: 1, md: 2, lg: 3, all: 0},
    loop: true,
    speed: 400,
    point: {
      visible: true
    },
    touch: true,
    easing: 'ease'
  };`

Let's say I have 3 items in my carousel and I load up my carousel in desktop view size 'lg'. Since I have configured 'lg' to have 3 items, only one page is needed, and one point is displayed. This is correct.

Now I resize my browser to the 'xs' size, and 3 pages are needed to display my 3 items. The display of the points still remains at 1, where what should actually display is 3 points.

**Comment by sheikalthaf** [comment]
Hello,

I have fixed this issue already. This will be fixed in upcoming update .

Thanks

**Comment by sheikalthaf** [comment]
This bug is fixed in the build 1.3.0.
Thanks for reporting
