### ISSUE TITLE
Component source code missing

### ISSUE THREAD

**Issue by neo** [sheikalthaf/ngx-carousel#3]
Hi first of all, very nice job doing this! I really appreciate it.

But when I take a look at `src/carousel.module.ts`, I see that the component source code should be at `src//carousel.component`. But I don't see such a file.

**Comment by sheikalthaf** [comment]
Yes source file is not uploaded.

**Comment by sheikalthaf** [comment]
Thanks for your appreciation

**Comment by neo** [comment]
But isn't it supposed to be open source? That way people could contribute to the project.

**Comment by sheikalthaf** [comment]
I don't have any intention to hide it. I'm just structuring the functions so that others can understand. I'm pushing it very soon

Cheers,
Sheik Althaf

**Comment by neo** [comment]
That would be great! Thank you again!
Also want to mention an actual issue: when the user is at the first slide and clicks to the left, it goes all the way to the right instead of going left one slide.

**Comment by neo** [comment]
And just for the record, I wasn't saying you were trying to hide the source. It was just a question. I really appreciate your work and care to explain. 😉

**Comment by sheikalthaf** [comment]
Source code now in the repo. check it and close this issue

**Comment by neo** [comment]
Yes, I saw your commit. Thank you again!
