### ISSUE TITLE
Is there any refresh, reload or destroy method?

### ISSUE THREAD

**Issue by musaay** [sheikalthaf/ngx-carousel#31]

**Comment by sheikalthaf** [comment]
Currently No but i will add it for you.

I want more information

For what purpose you want this

Thanks

**Comment by icepoint0** [comment]
can i  have some methods to jump to special index's image?

such as  method  jump(3) , and it will slide to third image.

**Comment by icepoint0** [comment]
at last i find it in source code :  moveTo(i) .

**Comment by musaay** [comment]
I wanna create dynamic slider. So i must reload slider.

**Comment by icepoint0** [comment]
@musaay you can use ngFor or extend carouselComponent to add some methods

**Comment by masloord** [comment]
so what was the solution to slide to a specific image in the carousel @icepoint0 @sheikalthaf

**Comment by musaay** [comment]
I think these methods should be added. Because it can be needed

**Comment by sheikalthaf** [comment]
I have already included the method to slide to the particular point number. `moveToSlide` is an input which accepts the number to slide.
I will push the update tomorrow with details. wait for the tomorrow update
Thanks for the suggestion

**Comment by sheikalthaf** [comment]
I have released the new build 1.3.0. read the changelog file

**Comment by musaay** [comment]
For example, you have a filter. I am searching and there are 20 products. Then I search with new criteria and no results are found. In this case, slider should destroy. How can i do that ?

**Comment by sheikalthaf** [comment]
@musaay I will try to implement this for you. but I cant tell the timeline of the implementation

**Comment by Ondrazar** [comment]
@sheikalthaf Also really need the ability to "reset" whole carousel (in ngOnChanges) so it behaevs like if I just started it for the first time. I am using the carousel in modal so my component doesn't get destroyed and nor does the carousel. 

Would really appreciate if you could implement something asap.

**Comment by saravanakumarkvk** [comment]
Hello Sheik,
I have simple fix to close this dynamic add values to the carousel. we need to call the transform function under buttoncontrol
 if(this.userData.grid[this.data.deviceType] >= this.carouselItems.length){
            this.setStyle(this.leftBtn, 'display', 'none');
            this.setStyle(this.rightBtn, 'display', 'none');
            
            this.transformStyle(0);
        }

**Comment by sheikalthaf** [comment]
@musaay @icepoint0 @masloord @Ondrazar @saravanakumarkvk  This carousel is depreciated. I actively maintaining the [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel) . This issue is fixed in [ngu-carousel](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.5)
