### ISSUE TITLE
How to set carousel to Fixed-Width?

### ISSUE THREAD

**Issue by codetinker** [sheikalthaf/ngx-carousel#32]
I had no problem setting the banner and tile. I do understand the grid.
But I just can't figure out how to set tile to fixed-width.

Tried this, but it is not what i wanted..:
`
<ngx-carousel [inputs]="carouselTile">

    <ngx-tile NgxCarouselItem *ngFor="let product of products" class="item" style="max-width:200px;">
        <div style="width:400px;">
            <product-single [product]="product"></product-single>
        </div>
    </ngx-tile>

    <button NgxCarouselPrev class='leftRs'>&lt;</button>
    <button NgxCarouselNext class='rightRs'>&gt;</button>
</ngx-carousel>
`

Setting:
`
this.carouselTile = {
      grid: {xs: 1, sm: 2, md: 3, lg: 4, all: 0},
      slide: 1,
      speed: 400,
      animation: 'lazy',
      point: {
        visible: true,
        pointStyles: ' .ngxcarouselPoint { display:none; }'
      },
      load: 2,
      touch: true,
      easing: 'ease'
    }
`

Help please.

**Comment by codetinker** [comment]
I missed reading the grid "all"
Works now.. 

`
<ngx-carousel [inputs]="carouselTile">

    <ngx-tile NgxCarouselItem *ngFor="let product of products" class="item">
        <div style="width:400px;">
            <product-single [product]="product"></product-single>
        </div>
    </ngx-tile>

    <button NgxCarouselPrev class='leftRs'>&lt;</button>
    <button NgxCarouselNext class='rightRs'>&gt;</button>
</ngx-carousel>
`

Grid setting:
`
grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 0},
`

Hope this helps others like me =)

**Comment by sheikalthaf** [comment]
Please close the issue if your problem solved.

Thanks

**Comment by jzfre** [comment]
Could you please provide a working example of use case with fixed width? 

Setting grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 0}  causes my browser to crash :/

**Comment by codetinker** [comment]
> Could you please provide a working example of use case with fixed width?
> 
> Setting grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 0} causes my browser to crash :/

These are my settings
`
  ngOnInit() {

    this.carouselTile = {
      grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 300},
      slide: 1,
      speed: 500,
      point: {
        visible: true,
        pointStyles: '
          .ngxcarouselPoint {
            list-style-type: none;
            text-align: center;
            padding: 12px;
            margin: 0;
            white-space: nowrap;
            overflow: auto;
            position: absolute;
            width: 100%;
            bottom: 5px;
            left: 0;
            box-sizing: border-box;
            z-index: 20;
            cursor:pointer;
          }
          .ngxcarouselPoint li {
            display: inline-block;
            border-radius: 999px;
            background: #E4E9F0;
            padding: 5px;
            margin: 0 3px;
            transition: .4s ease all;
          }
          .ngxcarouselPoint li.active {
              background: #0190FE;
              width: 10px;
          }
        '
      },
      load: 2,
      touch: true,
      easing: 'ease'
    }
  }
`

and the code
`
  <ngx-carousel [inputs]="carouselTile" (carouselLoad)="myfunc($event)">
    <ngx-tile NgxCarouselItem *ngFor="let item of items" class="item">
        <item-box [item]="item" [cart]="cart"></item-box>
    </ngx-tile>

    <span NgxCarouselPrev class="leftRs text-center">
        <i class="fa fa-chevron-left" aria-hidden="true"></i>
    </span>
    <span NgxCarouselNext class="rightRs text-center">
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </span>
  </ngx-carousel>
`
