### ISSUE TITLE
Hiding both arrows when all items is shown 

### ISSUE THREAD

**Issue by stlnk** [sheikalthaf/ngx-carousel#33]
Hello,
I have a question regarding how to hide both the previous and next arrows, when all items are shown (e.g total no of items are 2 and carousel view takes 3). Right now the 'next arrow' is visible even if they are no more items in the array.

**Comment by masloord** [comment]
I think you can add your own ngIf statement to hide the arrow if all items are shown

**Comment by sheikalthaf** [comment]
fixed this issue now. Available in the next update
Thanks

**Comment by sheikalthaf** [comment]
Fixed this bug in build 1.3.0. check the latest build and don't forget to read the changelog. close the issue if your problem solved

**Comment by stlnk** [comment]
Thank you, issue is solved. I'll close this issue.
