### ISSUE TITLE
touch sliding event not working

### ISSUE THREAD

**Issue by Max-Lev** [sheikalthaf/ngx-carousel#4]
cannot slide on touch event

**Comment by sheikalthaf** [comment]
Make sure you have passed "touch: true" in Inputs. by default it is false.

**Comment by sheikalthaf** [comment]
also check hammerjs is installed and imported. Refer readme file

**Comment by sheikalthaf** [comment]
Any info regarding this issue. If your problem resolved please close this issue

**Comment by sheikalthaf** [comment]
need info about your environment
angular version?
browser?

**Comment by Max-Lev** [comment]
Yes sorry, it works just fine.Tnx.

**Comment by sheikalthaf** [comment]
please close this issue. thank you
