### ISSUE TITLE
Interval not working

### ISSUE THREAD

**Issue by lihanyu23** [sheikalthaf/ngx-carousel#41]
Auto-sliding with fixed tempo does not working any more.

This is because in the latest commit [7ad00d94fbb445afab03db13665df4e3f9a279cc](https://github.com/sheikalthaf/ngx-carousel/commit/7ad00d94fbb445afab03db13665df4e3f9a279cc) the line 202 was commented

`+    // this.carouselInterval();`

Is there any reason to disable this feature?

**Comment by sheikalthaf** [comment]
update now available with this fix v1.3.1. I forgot to uncomment this.
Thanks for your information
