### ISSUE TITLE
In mobile when i try to scroll up or down on ngx-carousel item its moving left or right 

### ISSUE THREAD

**Issue by tamilvaanan** [sheikalthaf/ngx-carousel#48]
Hi,

When ngx-carousel item is displaying in mobile, I'm trying to move top of the page but current ngx-carousel item moving left or right .

thanks
Tamil

**Comment by iamlothian** [comment]
Duplicate #20

**Comment by sheikalthaf** [comment]
@tamilvaanan fixed this issue in build v1.3.0. read the changelog file
Thanks
