### ISSUE TITLE
Hiding the arrow when no more items

### ISSUE THREAD

**Issue by RichardBoyder** [sheikalthaf/ngx-carousel#5]
Hi there, how would i hide the left arrow when the first item is shown, and hide the right arrow when last item shown? What code would i put in the component typescript class of the component i have placed this into?

**Comment by sheikalthaf** [comment]
Hello,

   I'm pushing an update tomorrow with more features which includes this feature too. Use `loop: Boolean` after the tomorrow's update.





Thanks for your interest. Have a great day

**Comment by RichardBoyder** [comment]
Awesome thank you. this is a great component, Well done.

**Comment by RichardBoyder** [comment]
When the new code is up, how do we update our project? I used npm in a angular project...

**Comment by sheikalthaf** [comment]
writing the changelog... updating soon

**Comment by sheikalthaf** [comment]
option added in the latest update v1.1.0 . please update to the latest version and try it
