### ISSUE TITLE
Fixed Width Issue. 

### ISSUE THREAD

**Issue by Grundell** [sheikalthaf/ngx-carousel#54]
Hello -   I've been trying to get the fixed width version of the slider to work without success.. 

Following the previous issue:  #32 

As i understood it i need to set grid param to 0 on all accounts... 

This causes the app to totally break - see https://stackblitz.com/edit/angular-kll1f8.

**Comment by sheikalthaf** [comment]
```javascript
grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 250}
```
`all` denotes the fixed width. don't make it 0 when you need fixed width

**Comment by sheikalthaf** [comment]
@grundell Check the above code and it will solve your Issue

**Comment by Grundell** [comment]
@sheikalthaf  - Thank you that made a lot more sense.

**Comment by adam-gpc** [comment]
This crashes my website for me
