### ISSUE TITLE
Unable to change to third panel from second through the bottom dots

### ISSUE THREAD

**Issue by zorek11** [sheikalthaf/ngx-carousel#57]
If you select the second dot and then try to press the third nothing happens. I had 3 panels total when this error occurred.

**Comment by sheikalthaf** [comment]
I already fixed the issue will check again.

Thanks

**Comment by sheikalthaf** [comment]
This issue is already fixed.
What's your carousel version?

**Comment by sheikalthaf** [comment]
@zorek11 fixed the issue in build v1.3.5

**Comment by zorek11** [comment]
Thanks! @sheikalthaf
