### ISSUE TITLE
Cannot Move from 2nd to 3rd Slides and Peer Dependencies not supporting angular 5

### ISSUE THREAD

**Issue by Faran52** [sheikalthaf/ngx-carousel#59]
I'm using it on Angular 5, I cannot move specifically from Dot 2 to Dot 3 but works with next or drag.
Update: only happens when slide option is greater than 1

**Comment by sheikalthaf** [comment]
@Faran52  will you please create a plunkr for this issue. it will be good to find the bug

**Comment by Moelgaard85** [comment]
When using ngx-carousel with Angular 5 and running "npm install" there is warning:

ngx-carousel@1.3.3 requires a peer of @angular/core@^2.4.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-carousel@1.3.3 requires a peer of @angular/common@^2.4.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Faran52** [comment]
https://plnkr.co/edit/eSbmB1?p=preview Here I cannot navigate from slide2 to slide 3 if grid is greater than 2 but it works if jumping from slide 4 to backwards slide 3 or any other slides just not slide2->slide3 not working and also peer dependencies warning for angular 5

**Comment by sheikalthaf** [comment]
@Faran52 @Moelgaard85 This library only support angular 2.
But I'm already maintaining another library to support angular 4+ with universal support [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel)

**Comment by Faran52** [comment]
OK Will check that out, so that means the issue is only because of deprecation ?

**Comment by sheikalthaf** [comment]
@Faran52 thanks for the plunkr fixed the issue will push the update now

**Comment by Faran52** [comment]
Ok thanks

**Comment by Moelgaard85** [comment]
@sheikalthaf I will check out the ngu-carousel you mentioned.
