### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jbojcic1** [sheikalthaf/ngx-carousel#6]
Is there a demo where I can see how this carousel looks?

**Comment by neo** [comment]
It's in the repo link: https://sheikalthaf.github.io/ngx-carousel/

**Comment by sheikalthaf** [comment]
Actually this demo is outdated. I'm uploading the updated demo tomorrow. Please check back tomorrow

**Comment by sheikalthaf** [comment]
demo added with new options. check the repo. Also updated with new component and options.

**Comment by vanackej** [comment]
@sheikalthaf Is your demo site source code available somewhere ?
