### ISSUE TITLE
ngx-carousel right to left

### ISSUE THREAD

**Issue by mbmahyar** [sheikalthaf/ngx-carousel#62]
Hi, I want to reverse slider for Persian language so slider behavior reverse. 

 so i want

Next [10] [9] [8] [7] [6] [5] [4] [3] [2] [1] Prevoius

**Comment by sheikalthaf** [comment]
@Mahyar-Mb I already got this request. I will update you once it will get ready

**Comment by danielyaakove** [comment]
hi, Great component. I also need support to rtl.
I'm currently using bootstrap rtl grid and ngx-carousel Do not scroll to hidden items.

**Comment by sheikalthaf** [comment]
@Mahyar-Mb @danielyaakove @iamlothian `RTL` option is added to the [@ngu/carousel](https://github.com/sheikalthaf/ngu-carousel) v1.4.1.
Check the release [@ngu/carousel](https://github.com/sheikalthaf/ngu-carousel) for changelog

**Comment by Mahyar-Mb** [comment]
its awesome , thanks @sheikalthaf

**Comment by sheikalthaf** [comment]
This carousel is depreciated. I actively maintaining the [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel) . This issue is fixed in [ngu-carousel](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.5)
