### ISSUE TITLE
Arrows don't display on load

### ISSUE THREAD

**Issue by nijatKyra** [sheikalthaf/ngx-carousel#65]
Arrows are set to 'display: none' when the tiles are loaded. Only after moving the tiles arrows are shown.

Is there a way to show the arrows form the beginning?

**Comment by sheikalthaf** [comment]
hi,
You have to make `loop: true` to display buttons
play with `loop` option

**Comment by nijatKyra** [comment]
But I don't want it to loop. I need the left one to not show when the view is all the way to the left and vice versa (which works).

It's just the arrows don't appear when it loads. Only appear after I drag the screen (which I will disable for the purpose of my application). If I disable dragging then there is no way to navigate the carousel since the arrows only appear after a move

**Comment by nijatKyra** [comment]
Also carouselLoad doesn't fire for some reason

**Comment by sheikalthaf** [comment]
@nijatKyra are you using `rtl‘?

**Comment by nijatKyra** [comment]
what's `rtl'?

**Comment by nijatKyra** [comment]
Further debugging it seems like the arrows are displayed if I render the app in smaller dimensions. So when I run the app inside iPhone emulator, the arrows display fine. But if I display them in standard web resolution the arrows only appear after tiles have been moved

**Comment by sheikalthaf** [comment]
@nijatKyra show me the config of the carousel.
RTL means Right to Left direction

**Comment by nijatKyra** [comment]
No not using rtl

this.carouselTile = {
            grid: { xs: 1, sm: 1, md: 3, lg: 3, all: 0 },
            slide: 1,
            speed: 400,
            animation: 'lazy',
            point: {
                visible: true,
                pointStyles: `
                  .ngxcarouselPoint {
                    list-style-type: none;
                    text-align: center;
                    padding: 12px;
                    margin: 0;
                    white-space: nowrap;
                    overflow: auto;
                    position: absolute;
                    width: 100%;
                    top: 0;
                    box-sizing: border-box;
                  }
                  .ngxcarouselPoint li {
                    display: inline-block;
                    border-radius: 999px;
                    background: #444444;
                    width: 10px;
                    height: 10px;
                    padding: 5px;
                    margin: 2.5px 3px;
                    transition: .2s ease all;
                  }
                  .ngxcarouselPoint li.active {
                      background: white;
                      width: 15px;
                      height: 15px;
                      margin: 0px 3px;
                      border: 0.5px solid #444444;
                  }
                `
            },
            load: 2,
            touch: true,
            easing: 'cubic-bezier(0, 0, 0.2, 1)'
        }

**Comment by sheikalthaf** [comment]
@nijatKyra @iamlothian I tried the same config everything is fine. Will you please create a plunker

**Comment by nijatKyra** [comment]
The problem was a manual z-index overlapping the arrows. I just had to set z-index of the arrows to 99 and it fixed it.

It was a silly mistake
