### ISSUE TITLE
reload function in carousel

### ISSUE THREAD

**Issue by danishwebindia** [sheikalthaf/ngx-carousel#70]
can i refresh or reload carousel

**Comment by sheikalthaf** [comment]
@danishwebindia  This carousel is depreciated. I actively maintaining the [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel) . This issue is fixed in [ngu-carousel](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.5)
