### ISSUE TITLE
[moveToSlide] doesn't seem to be working

### ISSUE THREAD

**Issue by aeldaly** [sheikalthaf/ngx-carousel#76]
In my html I have

```
<ngx-carousel [inputs]="questionSliderConfig" [moveToSlide]="slideIndex" (onMove)="onMove($event)">
```
in the component file I have:

```
slideIndex = 15;

onMove(ngxCarouselStore): void {
    console.log(ngxCarouselStore.currentSlide);
    // console.log(this.slideIndex);
    // this.slideIndex = this.slideIndex + 4;
    // console.log(ngxCarouselStore.currentSlide);
    // console.log(this.slideIndex);
    // this.slideIndex = ngxCarouselStore.currentSlide;
  }
```

Which logs `1`

I tried putting a number directly instead so that it's `[moveToSlide]="14"` and that still shows the very first slide.

Is there something I'm missing?

Thanks!

**Comment by aeldaly** [comment]
Also, is there a way to prevent the transition inside `onMove` based on a condition?

**Comment by sheikalthaf** [comment]
@aeldaly `[moveToSlide]="14"` Works based on the carousel points not with tiles or items. if your number is greater than points then it will not move

**Comment by aeldaly** [comment]
I have more than 14 items in there @sheikalthaf

**Comment by aeldaly** [comment]
Even this doesn't seem to work:

`<ngx-carousel [inputs]="questionSliderConfig" [moveToSlide]="2" (onMove)="onMove($event)">`

Could this be a race condition? or does `moveToSlide` know to wait until all items are fetched and rendered?

**Comment by sheikalthaf** [comment]
@aeldaly @iamlothian This carousel is depreciated. I actively maintaining the [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel) . This issue is fixed in [ngu-carousel](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.5)
