### ISSUE TITLE
ngx-carousel not supporting Server side rendering with angular universal

### ISSUE THREAD

**Issue by ahmedBassell** [sheikalthaf/ngx-carousel#77]
when building for server side i got error:
```
})(window, document, 'Hammer');
   ^
ReferenceError: window is not defined
```

**Comment by sheikalthaf** [comment]
@ahmedBassell I already release the universal version in [@ngu/carousel](https://github.com/sheikalthaf/ngu-carousel)
Go and install the universal version

**Comment by kenji-1996** [comment]
Should be an easy fix for this current package to support it (Much like material does) by using the instance imported in main.ts instead of also importing it yourself
