### ISSUE TITLE
ngx-carousel not showing all the objects

### ISSUE THREAD

**Issue by hesampour** [sheikalthaf/ngx-carousel#8]
Hello
I have problem using the tile version of ngx-carousel. it not sows all the objects but just a subset of the object. for example if I set the lg in grid to 6 it just shows 6 items and others leave blank when scrolling

**Comment by hesampour** [comment]
the problem was with the rtl layout that i had used. I put the carousel in a container with ltr layout

**Comment by sheikalthaf** [comment]
after using LTR your problem resolved?

**Comment by hesampour** [comment]
yes it works fine now. thanks.
just it had some problem with moving slides that when I set loop to tru it solved

**Comment by sheikalthaf** [comment]
Hope you like the carousel. I'm closing the issue
