### ISSUE TITLE
Touch events not working

### ISSUE THREAD

**Issue by KevinShiCA** [sheikalthaf/ngx-carousel#80]
Angular version: 5.0.1
Browser: Chrome, others untested
HammerJS version: 2.0.8

I have HammerJS installed and imported into my app module, as per the readme.

My config:
```
this.carousel = {
   grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
   slide: 3,
   speed: 400,
   interval: 4000,
   point: {
      visible: true
   },
   load: 2,
   touch: true,
   loop: true,
   custom: 'banner'
}
```

There are 3 slides total.
Each `NgxCarouselItem` contains a single img tag with the following styles:
```
.carousel-img {
  width: 100%;
  height: calc(88vh - 50px);
  object-fit: cover;
}
```

All other controls are working perfectly. Any help appreciated.

**Comment by sheikalthaf** [comment]
This carousel is depreciated go and download the [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel) with universal support. And follow the guide there

**Comment by KevinShiCA** [comment]
Thank you, closing the issue.
