### ISSUE TITLE
Can't bind to 'inputs' since it isn't a known property of 'ngx-carousel'

### ISSUE THREAD

**Issue by sajidali2444** [sheikalthaf/ngx-carousel#82]
hi, i am using angular version 5.2.1 its throwing error like Can't bind to 'inputs' since it isn't a known property of 'ngx-carousel'
any solution, please.

**Comment by sajidali2444** [comment]
Eventually, i resolved my issue by adding NgxCarouselModule in shared module which used by every other module. now it is working fine now.

**Comment by sheikalthaf** [comment]
Thanks for the information. This carousel is depreciated go and download the [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel) with universal support

**Comment by link25** [comment]
@sajidali2444 Can you please explain more what you did to resolve this issue, because for me it's already declared in app.module but I still got the problem.

**Comment by sajidali2444** [comment]
@link25 I resolved it by using in the SharedModule and shared module is used by every other module.
I prefer you should also use a shared module. 
as you can check my previous answer
i resolved my issue by adding NgxCarouselModule in a shared module which used by every other module. now it is working fine now

**Comment by adam-gpc** [comment]
I'm still having the same issue on ngu/carousel
