### ISSUE TITLE
CarouselModule has no export member CarouselModule

### ISSUE THREAD

**Issue by RichardBoyder** [sheikalthaf/ngx-carousel#9]
I made a mistake and broke my angular build by trying to update to angular 4.... so i have re added a new project , included the carousel as per instruction but i am getting this in my app.component.ts.

why would this be showing?

**Comment by sheikalthaf** [comment]
I'm sorry. please import `NgxCarouselModule` instead of `CarouselModule`

**Comment by sheikalthaf** [comment]
If your issue solved close this issue

**Comment by RichardBoyder** [comment]
i changed that now my carousels don't show ?

**Comment by RichardBoyder** [comment]
are there any options i must change or new options added?

**Comment by RichardBoyder** [comment]
my component:

import { Component, OnInit } from '@angular/core';
import { Carousel } from 'ngx-carousel';

@Component({
  selector: 'app-whygetsure',
  templateUrl: './whygetsure.component.html',
  styleUrls: ['./whygetsure.component.scss']
})
export class WhygetsureComponent implements OnInit {
  public carouselTileItems: Array<any>;
  public carouselTile: Carousel;
  constructor() { }
  ngOnInit() {
    this.carouselTileItems = [0, 1, 2, 3, 4, 5];
    this.carouselTile = {
      grid: {xs: 2, sm: 3, md: 3, lg: 3, all: 0},
      slide: 3,
      speed: 400,
      interval: 4000,
      animation: 'lazy',
      point: false,
      load: 6,
      touch: true,
      custom: 'tile',
      dynamicLength: true
    };
  }

  public carouselTileLoad(evt: any) {
    const len = this.carouselTileItems.length;
 }

}

**Comment by sheikalthaf** [comment]
In your inputs remove `custom: tile`. because `ngx-tile` component is added use that. check getstarted guide in readme file

**Comment by RichardBoyder** [comment]
sorry for being a idiot but where is the readme file?

**Comment by sheikalthaf** [comment]
https://github.com/sheikalthaf/ngx-carousel/blob/master/README.md

**Comment by RichardBoyder** [comment]
thanks, but still not working well, i see it now but not looping and auto looping. also acting a bit odd.
<ngx-tile>

is this correct:

<ngx-carousel 
            [inputs]="carouselTile" 
            [inputsLength]="carouselTileItems.length"
            (carouselLoad)="carouselTileLoad($event)" class="ngxcarouselwhygetsure">
                   
                <ngx-tile>
                      
                          <img src="./assets/images/whygetsure/smartproducts.svg" class="TileIcons" />
                          <h3>Smart products</h3>
                          <p>We’re reinvesting insurance and
                            aim to bring you innovative and
                            quality products.</p>
                     
                </ngx-tile>
                <ngx-tile>
                      
                            <img src="./assets/images/whygetsure/wepayout.svg" class="TileIcons" />
                        <h3>We pay out, fast</h3>
                        <p>Submit a claim and if all checks
                            out you’ll be paid out within 24
                            hours, guaranteed.</p>
                      
                    </ngx-tile>
                    <ngx-tile>
                     
                        <img src="./assets/images/whygetsure/heretoassist.svg" class="TileIcons" />
                        <h3>Here to assist</h3>
                        <p>Our world-class support team is
                            standing by to assist with any
                            questions you might have.</p>
                     
                    </ngx-tile>
                    <ngx-tile>
                      
                        <img src="./assets/images/whygetsure/paperlesssystem.svg" class="TileIcons" />
                        <h3>Paperless system</h3>
                        <p>Online applications and claims that ensures the most convenient procedure for our customers.</p>
                     
                    </ngx-tile>
                    <ngx-tile>
                      
                        <img src="./assets/images/whygetsure/costefficient.svg" class="TileIcons" />
                        <h3>Cost efficient</h3>
                        <p>We pass our substantial cost savings on to you through low monthly payments.</p>
                     
                    </ngx-tile>
                    <ngx-tile>
                      
                        <img src="./assets/images/whygetsure/alwaysavailable.svg" class="TileIcons" />
                        <h3>Always available</h3>
                        <p>Queries and claims are available to you 24 hours a day, 7 days a week and 365 days a year.</p>
                     
                    </ngx-tile>
                
              <button class='leftRs'><</button>
              <button class='rightRs'>></button>
          </ngx-carousel>

**Comment by RichardBoyder** [comment]
the back button doesn't work , when it shows up

**Comment by RichardBoyder** [comment]
Im going to have to use the old one. Both my banner and tile carousel are broken. including the custom css i made for them.. i think Adding the <ngx-tile> etc is no longer reading my class i added originally...

**Comment by RichardBoyder** [comment]
Perhaps i can just include the code you added into mine to hide and show the arrows when beginning and end. Sorry, must be something i did when trying to update to the new changes that didn't work for me.... But thankyou, this is a super awesome plugin.... keep at it...

**Comment by sheikalthaf** [comment]
inside ngx-tile make a div element and put your elements like this.
`<ngx-tile>
          <div class="myclass">
                 <img src="./assets/images/whygetsure/smartproducts.svg" class="TileIcons" />
                 <h3>Smart products</h3>
                  <p>We’re reinvesting insurance and
                        aim to bring you innovative and
                        quality products.</p>
          </div>
</ngx-tile>
`

and target your css like this 
`
.ngxcarouselwhygetsure .myclass {

}
`

**Comment by RichardBoyder** [comment]
ah i see
