### ISSUE TITLE
getting extra space

### ISSUE THREAD

**Issue by dummy64** [sheikalthaf/ngx-carousel#95]
![extra](https://user-images.githubusercontent.com/22761132/37564315-93096cd8-2ab9-11e8-8d5e-135b38dea2e3.png)

**Comment by dummy64** [comment]
can i know how to solve this?

**Comment by sheikalthaf** [comment]
@dummy64 Sorry about this. shall i have a stackblitz to find where the issue is because it is difficult to reproduce.

Thanks

**Comment by dummy64** [comment]
i am having 12 images
i want them in ngx carousel
for mobile: 2.5 images
for tablet: 4.5 images
for desktop :6 images
this is the configuration i used
grid: { xs: 2.5, sm: 3, md: 4.5, lg: 6, all: 0 },
**for desktop its working fine but for mobile and tablet its not working**

**Comment by dummy64** [comment]
o
